Repository gitcoinco/code_fund_ads, pull requests merged in 2020-05, with the labels that each got.

#1244 self-host fira sans webfont
  app/javascript/src/index.js
  app/javascript/themes/current/stylesheets/application.scss
  app/views/layouts/application.html.erb
  app/views/layouts/authentication.html.erb
  app/views/layouts/component_preview.html.erb
  package.json
  yarn.lock
Labels: approved

#1252 Add the ability to inline edit the advertiser on campaign_bundles#show
  app/helpers/application_helper.rb
  app/javascript/controllers/campaign_bundles_controller.js
  app/reflexes/campaign_bundles_reflex.rb
  app/views/campaign_bundles/show.html.erb
Labels: approved

#1250 add total_budget field to campaigns form for bundled campaigns
  app/views/campaigns/_form.html.erb
Labels: approved

#1255 Fix bash path for commands (support non-mac)
  bin/copy_production_db_to_local
  bin/copy_production_db_to_staging
  bin/generate_db_artifacts
  bin/heroku_pg_dump_production_replica
  bin/heroku_preboot_disable
  bin/heroku_preboot_enable
  bin/heroku_promote
Labels: approved

#1260 upgrade rails to 6.0.3
  .circleci/config.yml
  Gemfile.lock
  bin/standardize
  yarn.lock
Labels: approved

#1259 correctly polyfill features in the older browsers
  app/javascript/packs/code_fund.js
  app/javascript/packs/code_fund_ad.js
Labels: don't merge

#1266 bundle dates bug
  app/controllers/campaign_bundles_controller.rb
  app/models/campaign.rb
  app/models/campaign_bundle.rb
  app/reflexes/campaign_bundles_reflex.rb
Labels: approved

#1262 fix styling issue on creatives form
  app/views/creatives/_form.html.erb
Labels: approved

#1263 reduce heroku slug size
  .slugignore
  lib/tasks/assets.rake
Labels: approved

#1264 add url to organizations
  app/controllers/organizations_controller.rb
  app/helpers/application_helper.rb
  app/models/campaign.rb
  app/models/impression.rb
  app/models/organization.rb
  app/models/property.rb
  app/validators/url_validator.rb
  app/views/organizations/_form.html.erb
  app/views/organizations/_sidebar.html.erb
  app/views/properties/_sidebar.html.erb
  app/views/user_properties/_table.html.erb
  db/migrate/20200507164638_add_url_to_organizations.rb
  db/schema.rb
  db/structure.sql
  test/fixtures/impressions.yml
  test/fixtures/organizations.yml
  test/helpers/application_helper_test.rb
  test/models/impression_test.rb
  test/models/organization_test.rb
  test/models/property_test.rb
Labels: approved

#1268 Force date filters to match the current camapign being viewed/edited
  app/controllers/campaign_countries_controller.rb
  app/controllers/campaign_creatives_controller.rb
  app/controllers/campaign_dailies_controller.rb
  app/controllers/campaign_properties_controller.rb
  app/controllers/campaigns_controller.rb
  app/controllers/concerns/campaigns/dateable.rb
Labels: approved

#1271 Update nginx config to ensure origin IP
  config/nginx.conf.erb
Labels: approved

#1272 Revert nginx change, utilize CF-Connecting-IP
  .env-example
  app/controllers/advertisements_controller.rb
  app/models/property.rb
  config/nginx.conf.erb
Labels: approved

#1273 Update storage of IP and Country to use CF data
  app/controllers/advertisements_controller.rb
  app/controllers/impressions_controller.rb
  app/jobs/create_impression_job.rb
  test/jobs/create_impression_job_test.rb
Labels: approved

#1269 issue 1249
  .gitignore
  app/components/application_component.rb
  app/components/form/error_message_component.html.erb
  app/components/form/error_message_component.rb
  app/components/utm_table_component.html.erb
  app/components/utm_table_component.rb
  app/views/campaign_bundles/campaigns/_form.html.erb
  app/views/campaigns/_form.html.erb
  app/views/campaigns/_form.html.erb.tmp
  app/views/campaigns/form/_additional_targeting.html.erb
  app/views/campaigns/form/_budget.html.erb
  app/views/campaigns/form/_creatives.html.erb
  app/views/campaigns/form/_details.html.erb
  app/views/campaigns/form/_geo_targeting.html.erb
  app/views/creatives/_form.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/invitations/new.html.erb
  app/views/organization_reports/_form.html.erb
  app/views/organization_transactions/_form.html.erb
  app/views/organization_users/_form.html.erb
  app/views/organizations/_form.html.erb
  app/views/properties/_form.html.erb
  app/views/scheduled_organization_reports/_form.html.erb
  app/views/shared/forms/_error_messages.html.erb
  test/components/form/error_message_component_test.rb
  test/components/previews/form/error_message_component_preview.rb
  test/components/previews/utm_table_component_preview.rb
  test/components/utm_table_component_test.rb
Labels: approved

#1275 Clean up Cloudlflare IP with gem
  Gemfile
  Gemfile.lock
  app/controllers/advertisements_controller.rb
  config/initializers/cloudflare.rb
Labels: approved

#1274 Update labels and ordering on orgs sidebar metrics
  app/views/organizations/_sidebar.html.erb
Labels: approved

#1276 restore countries tab for campaigns
  app/helpers/campaigns_helper.rb
Labels: approved

#1251 Inbound Email parsing
  .env-example
  app/components/back_link_component.html.erb
  app/components/back_link_component.rb
  app/components/list_group_component.rb
  app/components/page/header_component.html.erb
  app/components/page/header_component.rb
  app/controllers/user_emails_controller.rb
  app/controllers/users_controller.rb
  app/helpers/user_emails_helper.rb
  app/helpers/users_helper.rb
  app/javascript/src/index.js
  app/javascript/themes/current/stylesheets/application.scss
  app/javascript/themes/current/stylesheets/components.scss
  app/javascript/themes/current/stylesheets/components/trix.scss
  app/mailboxes/application_mailbox.rb
  app/mailboxes/incoming_mailbox.rb
  app/models/authorized_user.rb
  app/models/concerns/authorizers/email.rb
  app/models/inbound_email.rb
  app/models/user.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/user_emails/_email_preview.erb
  app/views/user_emails/index.html.erb
  app/views/user_emails/show.html.erb
  app/views/users/form/_admin.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  config/sidekiq.yml
  db/migrate/20200504175333_create_action_mailbox_tables.action_mailbox.rb
  db/migrate/20200504194917_add_record_inbound_emails_to_users.rb
  db/migrate/20200505193112_create_inbound_emails.rb
  db/migrate/20200505203735_create_inbound_emails_users.rb
  db/migrate/20200511174710_create_action_text_tables.action_text.rb
  db/schema.rb
  db/structure.sql
  lib/tasks/misc.rake
  package.json
  test/components/back_link_component_test.rb
  test/controllers/advertisements_controller_test.rb
  test/controllers/user_emails_controller_test.rb
  test/fixtures/action_text/rich_texts.yml
  test/fixtures/users.yml
  test/jobs/link_inbound_email_to_users_job_test.rb
  test/mailboxes/incoming_mailbox_test.rb
  test/models/inbound_email_test.rb
  test/models/user_test.rb
  test/test_helper.rb
  yarn.lock
Labels: approved

#1289 upgrade to rails 6.0.3.1
  Gemfile.lock
  yarn.lock
Labels: approved

#1291 Update scripts to work with WSL2
  bin/copy_production_db_to_local
  bin/heroku_pg_dump_production_replica
Labels: approved

#1285 Outbound Emails
  app/components/email_component.html.erb
  app/components/email_component.rb
  app/components/emails/attachment_component.html.erb
  app/components/emails/attachment_component.rb
  app/components/emails/attachments_component.html.erb
  app/components/emails/attachments_component.rb
  app/components/emails/body_component.html.erb
  app/components/emails/body_component.rb
  app/components/emails/header_component.html.erb
  app/components/emails/header_component.rb
  app/components/emails/message_viewer_component.html.erb
  app/components/emails/message_viewer_component.rb
  app/controllers/emails_controller.rb
  app/helpers/emails_helper.rb
  app/javascript/themes/current/stylesheets/components.scss
  app/javascript/themes/current/stylesheets/components/emails.scss
  app/mailboxes/incoming_mailbox.rb
  app/models/email.rb
  app/models/email_user.rb
  app/models/user.rb
  app/views/emails/index.html.erb
  app/views/emails/show.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/shared/sidebar_content/_inbox.html.erb
  app/views/user_emails/show.html.erb
  bin/copy_production_db_to_local
  bin/copy_production_db_to_staging
  bin/source_env
  config/database.yml
  config/enums.yml
  config/initializers/date_formats.rb
  config/routes.rb
  db/migrate/20200513193432_create_emails.rb
  db/migrate/20200513210427_drop_inbound_emails.rb
  db/migrate/20200519191749_create_email_users.rb
  db/schema.rb
  db/structure.sql
  test/components/email_component_test.rb
  test/components/emails/attachment_component_test.rb
  test/components/emails/attachments_component_test.rb
  test/components/emails/body_component_test.rb
  test/components/emails/header_component_test.rb
  test/components/emails/message_viewer_component_test.rb
  test/fixtures/emails.yml
  test/mailboxes/incoming_mailbox_test.rb
  test/models/email_test.rb
  test/models/email_user_test.rb
  test/models/inbound_email_test.rb
Labels: approved, has conflicts

#1295 Bug fix - User limit to their own campaigns
  .gitignore
  app/controllers/demos_controller.rb
  app/views/demos/show.html.erb
  bin/copy_production_db_to_local
Labels: approved

#1303 Do not record internal email communications
  app/models/user.rb
  test/fixtures/users.yml
  test/mailboxes/incoming_mailbox_test.rb
Labels: approved

#1301 Berry/1281 missing country flags
  app/components/application_component.rb
  app/components/comments/comment_component.html.erb
  app/components/comments/rich_text_form_component.html.erb
  app/components/comments/rich_text_form_component.rb
  app/components/comments_component.html.erb
  app/controllers/comments_controller.rb
  app/javascript/controllers/comments_component_controller.js
  app/javascript/themes/current/stylesheets/components.scss
  app/javascript/themes/current/stylesheets/components/emails.scss
  app/javascript/themes/current/stylesheets/components/trix.scss
  app/models/comment.rb
  app/models/concerns/daily_summary_reports/presentable.rb
  app/models/daily_summary_report.rb
  app/views/campaign_countries/_tr.html.erb
  config/initializers/date_formats.rb
  lib/tasks/misc.rake
  test/components/comments/comment_component_test.rb
  test/components/comments/rich_text_form_component_test.rb
  test/models/comment_test.rb
Labels: approved

#1299 Pre-populate creative images when cloned
  .circleci/config.yml
  app/controllers/creatives_controller.rb
  app/models/creative.rb
  app/models/image.rb
  app/views/creatives/_form.html.erb
Labels: approved

#1302 Indicate if creative or property is not actively being used by campaign
  app/helpers/application_helper.rb
  app/helpers/frontend/table_helper.rb
  app/views/campaign_creatives/_table.html.erb
  app/views/campaign_creatives/_tr.html.erb
  app/views/campaign_properties/_table.html.erb
  app/views/campaign_properties/_tr.html.erb
Labels: approved

#1305 fix: stop total budget from updating when daily budget is changed
  app/models/concerns/campaigns/budgetable.rb
  test/integration/advertisements_test.rb
Labels: approved

#1307 chore: upgrade puma to 4.3.5 to address CVE-2020-11077
  Gemfile.lock
Labels: approved

#1308 Use square ad template for creative previews and add CTA to preview
  app/javascript/controllers/creative_form_controller.js
  app/javascript/themes/current/stylesheets/components/creative_preview.scss
  app/views/creatives/_form.html.erb
Labels: approved

#1309 Add button to campaign pages that sets the date range to the campaign's date range
  app/controllers/campaign_countries_controller.rb
  app/controllers/campaign_creatives_controller.rb
  app/controllers/campaign_dailies_controller.rb
  app/controllers/campaign_properties_controller.rb
  app/controllers/campaigns_controller.rb
  app/controllers/concerns/campaigns/dateable.rb
  app/views/campaign_comments/index.html.erb
  app/views/campaign_countries/index.html.erb
  app/views/campaign_creatives/index.html.erb
  app/views/campaign_dailies/index.html.erb
  app/views/campaign_properties/index.html.erb
  app/views/campaigns/show.html.erb
Labels: approved
