Repository gitcoinco/code_fund_ads, pull requests merged in 2020-02, with the labels that each got.

#1092 add github action for labeling approved pull requests
  .github/workflows/label_approved_pull_requests.yml
Labels: approved

#1091 add the ability to enable/disable scout with environment variable
  .env-example
  config/scout_apm.yml
Labels: approved, needs env update

#1093 fix invite user button on Users#index
  app/views/users/index.html.erb
Labels: approved

#1096 Update name/label for north america
  app/models/region.rb
  bin/copy_production_db_to_staging
Labels: approved

#1097 add the auto-height controller back in
  app/javascript/controllers/auto_height_controller.js
  app/views/shared/_layout.html.erb
Labels: approved

#1098 fix console errors related to meta tags
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
  app/views/layouts/authentication.html.erb
  app/views/layouts/demo.html.erb
Labels: approved

#1100 small tweaks to inventory tables for campaign bundles
  app/views/campaign_bundles/_inventory.html.erb
  app/views/campaign_bundles/campaigns/_inventory.html.erb
Labels: approved

#1101 Setup new activity indicator
  Gemfile
  Gemfile.lock
  app/controllers/concerns/campaign_bundles/stashable.rb
  app/javascript/controllers/activity_indicator_controller.js
  app/javascript/controllers/application_controller.js
  app/views/campaign_bundles/_form.html.erb
  app/views/campaign_bundles/campaigns/_form.html.erb
  app/views/shared/_activity_indicator.html.erb
  app/views/shared/sidebar_content/_footer_current_organization.html.erb
  package.json
  yarn.lock
Labels: approved

#1102 Get bundle save working
  app/controllers/campaign_bundles_controller.rb
  app/views/campaign_bundles/_form.html.erb
  app/views/campaign_bundles/_list_group_item.html.erb
  app/views/campaign_bundles/campaigns/_form.html.erb
  app/views/shared/_header.html.erb
Labels: approved

#1071 update the csl gem
  Gemfile
  Gemfile.lock
  app/jobs/check_consolidated_screening_list_job.rb
Labels: needs env update

#1105 fix cloned campaigns form
  app/controllers/campaigns_controller.rb
  app/controllers/concerns/campaigns/stashable.rb
Labels: approved

#1104 fix sorting on users index
  app/controllers/users_controller.rb
Labels: approved

#1106 default property_type to website
  app/models/property.rb
  app/views/properties/_form.html.erb
  db/migrate/20200221220825_add_property_type_default_to_properties.rb
  db/schema.rb
  db/structure.sql
  test/factories/properties.rb
  test/fixtures/properties.yml
  test/models/property_test.rb
Labels: approved

#1109 Add back pressure check on ad render
  .env-example
  app/controllers/advertisements_controller.rb
  config/initializers/okcomputer.rb
  config/initializers/rack_attack.rb
Labels: approved

#1111 Update staging pg_restore
  bin/copy_production_db_to_staging
  bin/heroku_pg_dump_production_replica
Labels: approved

#1112 Ensure we use Rails' remote_ip value in rack attack check
  config/application.rb
  config/initializers/rack_attack.rb
Labels: approved

#1115 Add CTR to campaign bundle builder
  app/models/daily_summary.rb
  app/models/inventory_detail.rb
  app/models/inventory_summary.rb
  app/views/campaign_bundles/_inventory.html.erb
  app/views/campaign_bundles/campaigns/_inventory.html.erb
Labels: approved

#1116 Include org balance in budget check
  app/jobs/ensure_scoped_daily_summaries_job.rb
  app/models/concerns/campaigns/budgetable.rb
  config/sidekiq.yml
Labels: approved

#1117 Cuprite
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  test/application_system_test_case.rb
  test/system/ads_bottom_bar_javascript_test.rb
  test/system/ads_centered_javascript_test.rb
  test/system/ads_default_javascript_test.rb
  test/system/ads_docsify_javascript_test.rb
  test/system/ads_horizontal_javascript_test.rb
  test/system/ads_image_only_javascript_test.rb
  test/system/ads_rectangle_narrow_javascript_test.rb
  test/system/ads_sponsored_text_javascript_test.rb
  test/system/ads_square_javascript_test.rb
  test/system/ads_sticky_box_javascript_test.rb
  test/system/ads_text_javascript_test.rb
  test/system/ads_top_bar_javascript_test.rb
  test/system/ads_vertical_javascript_test.rb
Labels: approved

#1118 Setup isolated worker for daily summary rollup creation
  Procfile
  app/jobs/create_daily_summaries_job.rb
  app/jobs/create_daily_summary_job.rb
  app/jobs/ensure_daily_summaries_job.rb
  app/jobs/ensure_scoped_daily_summaries_job.rb
  config/sidekiq.yml
  config/sidekiq_daily_summaries.yml
Labels: approved

#1114 Update and remove unused gems
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/models/campaign.rb
  app/models/campaign_bundle.rb
  app/models/coupon.rb
  app/models/daily_summary.rb
  app/models/daily_summary_report.rb
  app/models/event.rb
  app/models/impression.rb
  app/models/job_posting.rb
  app/models/organization.rb
  app/models/organization_report.rb
  app/models/organization_transaction.rb
  app/models/property.rb
  app/models/property_traffic_estimate.rb
  app/models/scheduled_organization_report.rb
  app/models/user.rb
  config/initializers/airbrake.rb
  config/initializers/heroku_language_metrics.rb
  gem_graph.png
  test/factories/campaigns.rb
  test/factories/impressions.rb
  test/factories/organization_reports.rb
  test/factories/organizations.rb
  test/factories/properties.rb
  test/factories/scheduled_organization_reports.rb
  test/factories/users.rb
  test/fixtures/campaign_bundles.yml
  test/fixtures/campaigns.yml
  test/fixtures/coupons.yml
  test/fixtures/daily_summaries.yml
  test/fixtures/events.yml
  test/fixtures/impressions.yml
  test/fixtures/job_postings.yml
  test/fixtures/organizations.yml
  test/fixtures/properties.yml
  test/fixtures/property_traffic_estimates.yml
  test/fixtures/users.yml
  test/models/campaign_bundle_test.rb
  test/models/campaign_test.rb
  test/models/coupon_test.rb
  test/models/daily_summary_test.rb
  test/models/event_test.rb
  test/models/impression_test.rb
  test/models/job_posting_test.rb
  test/models/organization_report_test.rb
  test/models/organization_test.rb
  test/models/organization_transaction_test.rb
  test/models/property_test.rb
  test/models/property_traffic_estimate_test.rb
  test/models/scheduled_organization_report_test.rb
  test/models/user_test.rb
  test/test_helper.rb
Labels: approved

#1107 JavaScript cleanup and dependency updates
  app/javascript/controllers/copy_to_clipboard_controller.js
  app/javascript/controllers/cube_folio_controller.js
  app/javascript/controllers/dashboard_date_range_controller.js
  app/javascript/controllers/easy_pie_chart_controller.js
  app/javascript/controllers/event_track_controller.js
  app/javascript/controllers/fallback_image_controller.js
  app/javascript/controllers/file_picker_controller.js
  app/javascript/controllers/go_to_controller.js
  app/javascript/controllers/inline_toggle_controller.js
  app/javascript/controllers/job_listing_keyword_controller.js
  app/javascript/controllers/job_posting_prospects_form_controller.js
  app/javascript/controllers/job_posting_purchases_form_controller.js
  app/javascript/controllers/load_more_controller.js
  app/javascript/controllers/master_detail_controller.js
  app/javascript/controllers/mega_menu_controller.js
  app/javascript/controllers/organization_users_search_controller.js
  app/javascript/controllers/radio_button_group_controller.js
  app/javascript/controllers/rich_text_editor_controller.js
  app/javascript/controllers/search_autocomplete_controller.js
  app/javascript/controllers/search_controller.js
  app/javascript/controllers/select_child_controller.js
  app/javascript/controllers/select_country_province_controller.js
  app/javascript/controllers/select_date_range_controller.js
  app/javascript/controllers/select_parent_controller.js
  app/javascript/controllers/sticky_block_controller.js
  app/javascript/controllers/submit_on_enter_controller.js
  app/javascript/controllers/svg_injector_controller.js
  app/javascript/events/value_committed_event.js
  app/javascript/themes/current/index.js
  app/javascript/themes/current/stylesheets/application.scss
  app/javascript/themes/current/stylesheets/theme.scss
  app/views/referrals/_share_card.html.erb
  app/views/shared/_date_range_picker.html.erb
  babel.config.js
  package.json
  vendor/themes/current/javascript/components/hs.clipboard.js
  yarn.lock
Labels: approved

#1120 Protect impressions from the user interface
  app/controllers/application_controller.rb
  app/models/concerns/impressionable.rb
  app/models/current.rb
Labels: approved

#1121 Remove n+1 on ad render
  app/controllers/advertisements_controller.rb
  app/jobs/create_debit_for_campaign_and_date_job.rb
  app/jobs/create_debits_for_campaigns_job.rb
  app/models/concerns/campaigns/budgetable.rb
Labels: approved

#1122 update available index scopes and re-order tables
  app/controllers/campaign_properties_controller.rb
  app/controllers/property_campaigns_controller.rb
  app/views/campaign_bundles/index.html.erb
  app/views/campaign_properties/_table.html.erb
  app/views/campaigns/index.html.erb
  app/views/creatives/index.html.erb
  app/views/properties/index.html.erb
  app/views/property_campaigns/_table.html.erb
  config/initializers/pagy.rb
Labels: approved

#1123 update puma to address CVE-2020-5247
  Gemfile.lock
Labels: approved

#1124 downgrade puma due to auth token bug
  Gemfile
  Gemfile.lock
Labels: approved

#1126 Sanitize array params for campaigns forms
  app/controllers/application_controller.rb
  app/controllers/campaigns_controller.rb
Labels: approved
