Repository gitcoinco/code_fund_ads, pull requests merged in 2020-04, with the labels that each got.

#1189 Update messaging on administrator campaign rows
  app/views/administrator_dashboards/_tr.html.erb
Labels: approved

#1159 Cleanup more todos
  app/controllers/advertisements_controller.rb
  app/controllers/comments_controller.rb
  app/helpers/comments_helper.rb
  app/javascript/themes/current/stylesheets/components/navigation.scss
  app/models/campaign.rb
  app/views/comments/_table.html.erb
  app/views/comments/for_campaign/index.html.erb
  app/views/comments/for_organization/index.html.erb
  app/views/comments/for_property/index.html.erb
  app/views/comments/for_user/index.html.erb
  app/views/comments/index.html.erb
  app/views/shared/_comment.html.erb
  config/routes.rb
  test/controllers/comments_controller_test.rb
Labels: approved

#1191 upgrade to ruby 2.6.6
  .circleci/config.yml
  .mert-example
  .ruby-version
  .standard.yml
  .teamocil-example.yml
  .tmuxinator-example.yml
  Gemfile
  README.md
Labels: approved

#1190 Change how we are pulling the maxmind db
  Gemfile.lock
  app/jobs/download_and_extract_maxmind_file_job.rb
  config/initializers/maxmind.rb
  test/jobs/download_and_extract_maxmind_files_job_test.rb
  test/jobs/download_maxmind_files_job_test.rb
Labels: approved

#1193 Update packages for security vulnerabilities
  .env-example
  Gemfile
  Gemfile.lock
  app/javascript/src/index.js
  app/javascript/themes/current/stylesheets/application.scss
  app/javascript/themes/current/stylesheets/components.scss
  app/javascript/themes/current/stylesheets/components/accordians.scss
  app/javascript/themes/current/stylesheets/components/cards.scss
  app/javascript/themes/current/stylesheets/components/checkbox_tree.scss
  app/javascript/themes/current/stylesheets/components/tables.scss
  app/javascript/themes/current/stylesheets/mixins.scss
  app/javascript/themes/current/stylesheets/theme.scss
  app/javascript/themes/current/stylesheets/theme_variables.scss
  app/javascript/themes/current/stylesheets/utilities.scss
  app/javascript/themes/current/stylesheets/variables.scss
  app/views/campaigns/show.html.erb
  app/views/demos/show.html.erb
  app/views/organizations/show.html.erb
  app/views/properties/show.html.erb
  app/views/property_dashboards/show.html.erb
  app/views/shared/_collapsible_search_form.html.erb
  bin/clear_circleci_cache
  gem_graph.png
  package.json
  yarn.lock
Labels: approved

#1194 update standard
  Gemfile.lock
  app/controllers/advertisement_clicks_controller.rb
  app/controllers/advertisement_previews_controller.rb
  app/controllers/images_controller.rb
  app/controllers/impressions_controller.rb
  app/controllers/job_posting_prospects_controller.rb
  app/controllers/job_posting_purchases_controller.rb
  app/controllers/job_posting_searches_controller.rb
  app/controllers/job_posting_users_controller.rb
  app/controllers/organization_invites_controller.rb
  app/controllers/organization_reports_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/properties_controller.rb
  app/controllers/scheduled_organization_reports_controller.rb
  app/controllers/user_passwords_controller.rb
  app/helpers/frontend/link_helper.rb
  app/jobs/create_organization_report_job.rb
  app/mailers/campaigns_mailer.rb
  app/mailers/properties_mailer.rb
  app/mailers/users_mailer.rb
  app/models/concerns/properties/reportable.rb
  app/models/concerns/users/stripeable.rb
  app/models/province.rb
  test/models/organization_test.rb
  test/models/organization_user_test.rb
Labels: approved

#1197 Add alerts for missing resources for campaigns and creatives
  app/helpers/organizations_helper.rb
  app/models/concerns/authorizers/image.rb
  app/models/concerns/organizations/imageable.rb
  app/views/campaigns/_form.html.erb
  app/views/creatives/_form.html.erb
  app/views/creatives/forms/_sponsor_form.html.erb
  app/views/creatives/forms/_standard_form.html.erb
  app/views/shared/_alert.html.erb
  config/locales/en.yml
Labels: approved

#1200 write entire maxmind response body to file instead of reading in chunks
  app/jobs/download_and_extract_maxmind_file_job.rb
Labels: approved

#1202 prevent `undefined method 'name' for nil:NilClass` error in header
  app/views/shared/_header.html.erb
Labels: approved

#1201 drop comments table
  Gemfile
  Gemfile.lock
  PROSPECTUS.md
  app/models/campaign.rb
  app/models/comment.rb
  app/models/organization.rb
  app/models/property.rb
  app/models/user.rb
  db/migrate/20200406223804_drop_comments_table.rb
  db/schema.rb
  db/structure.sql
Labels: approved

#1204 update nginx config based on feedback
  config/nginx.conf.erb
Labels: approved

#1203 Add view component and create avatar component
  Gemfile
  Gemfile.lock
  app/components/users/avatar_component.html.erb
  app/components/users/avatar_component.rb
  app/helpers/users_helper.rb
  app/javascript/controllers/index.js
  app/views/creatives/_list_group_item.html.erb
  app/views/layouts/application.html.erb
  app/views/organization_users/_tr.html.erb
  app/views/properties/_list_group_item.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_page_titlebar.html.erb
  app/views/shared/_sidebar.html.erb
  app/views/users/_card.html.erb
  app/views/users/_layout.html.erb
  app/views/users/_list_group_item.html.erb
  app/views/users/_table.html.erb
  app/views/users/_tr.html.erb
  app/views/users/for_organization/index.html.erb
  app/views/users/form/_avatar.html.erb
  config/application.rb
  test/components/previews/users/avatar_component_preview.rb
  test/components/users/avatar_component_test.rb
  test/test_helper.rb
Labels: approved

#1206 send rollbar more information when we get an undefined conversion error
  app/controllers/impressions_controller.rb
Labels: approved

#1207 update bundle dates text to not look like a warning on campaigns form
  app/views/campaigns/_form.html.erb
Labels: approved

#1211 Assist datepicker to match selected campaigns for reports
  app/controllers/organization_reports_controller.rb
  app/javascript/controllers/organization_report_controller.js
  app/views/organization_reports/_card.html.erb
  app/views/organization_reports/_form.html.erb
Labels: approved

#1212 force encode user agent to utf-8 and show encoding in rollbar error
  app/controllers/impressions_controller.rb
Labels: approved

#1217 update gems and run annotate
  Gemfile
  Gemfile.lock
  app/models/campaign.rb
  app/models/campaign_bundle.rb
  app/models/coupon.rb
  app/models/daily_summary.rb
  app/models/daily_summary_report.rb
  app/models/event.rb
  app/models/impression.rb
  app/models/job_posting.rb
  app/models/organization.rb
  app/models/organization_report.rb
  app/models/organization_transaction.rb
  app/models/property.rb
  app/models/property_traffic_estimate.rb
  app/models/scheduled_organization_report.rb
  app/models/user.rb
  package.json
  test/fixtures/campaign_bundles.yml
  test/fixtures/campaigns.yml
  test/fixtures/coupons.yml
  test/fixtures/daily_summaries.yml
  test/fixtures/events.yml
  test/fixtures/impressions.yml
  test/fixtures/job_postings.yml
  test/fixtures/organizations.yml
  test/fixtures/properties.yml
  test/fixtures/property_traffic_estimates.yml
  test/fixtures/scheduled_organization_reports.yml
  test/fixtures/users.yml
  test/models/campaign_bundle_test.rb
  test/models/campaign_test.rb
  test/models/coupon_test.rb
  test/models/daily_summary_test.rb
  test/models/event_test.rb
  test/models/impression_test.rb
  test/models/job_posting_test.rb
  test/models/organization_report_test.rb
  test/models/organization_test.rb
  test/models/organization_transaction_test.rb
  test/models/property_test.rb
  test/models/property_traffic_estimate_test.rb
  test/models/scheduled_organization_report_test.rb
  test/models/user_test.rb
  yarn.lock
Labels: approved

#1218 Clean up generated PDF report
  app/assets/stylesheets/organization_report.scss
  app/controllers/organization_reports_controller.rb
  app/views/organization_reports/_table.html.erb
  app/views/organization_reports/pages/_campaign.html.erb
  app/views/organization_reports/pages/_campaign_summary.html.erb
  app/views/organization_reports/pages/_country_table.html.erb
  app/views/organization_reports/pages/_creative_table.html.erb
  app/views/organization_reports/pages/_daily_table.html.erb
  app/views/organization_reports/pages/_property_table.html.erb
Labels: approved, enhancement

#1219 Set current org when viewing user
  app/controllers/users_controller.rb
Labels: approved, enhancement

#1221 add a threshold of 5% variance between spend vs date pacing on admin dashboard
  app/models/concerns/campaigns/budgetable.rb
  app/views/administrator_dashboards/_tr.html.erb
Labels: approved

#1222 Use Metabase Admin Dashboard on admin dashboard page
  .env-example
  app/controllers/administrator_dashboards_controller.rb
  app/views/administrator_dashboards/show.html.erb
Labels: approved, needs env update

#1223 Gracefully handle missing summary
  app/models/concerns/campaigns/budgetable.rb
Labels: approved

#1225 Add ability to assign account manager to orgs
  app/controllers/organizations_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/organization.rb
  app/models/user.rb
  app/views/campaigns/_sortable_dropdown.html.erb
  app/views/campaigns/_table.html.erb
  app/views/campaigns/_tr.html.erb
  app/views/campaigns/index.html.erb
  app/views/organizations/_form.html.erb
  app/views/organizations/_sidebar.html.erb
  config/enums.yml
  db/migrate/20200416182239_add_account_manager_user_id_to_organizations.rb
  db/schema.rb
  db/structure.sql
  test/fixtures/organizations.yml
  test/models/organization_test.rb
Labels: approved

#1226 Update campaign bundle builder
  Gemfile
  Gemfile.lock
  app/helpers/campaign_bundles_helper.rb
  app/javascript/themes/current/stylesheets/utilities.scss
  app/models/campaign.rb
  app/models/campaign_bundle.rb
  app/models/concerns/campaigns/presentable.rb
  app/models/inventory_detail.rb
  app/models/inventory_summary.rb
  app/reflexes/campaign_bundles_reflex.rb
  app/views/campaign_bundles/_form.html.erb
  app/views/campaign_bundles/_inventory.html.erb
  app/views/campaign_bundles/campaigns/_form.html.erb
  app/views/campaign_bundles/campaigns/_inventory.html.erb
  package.json
  yarn.lock
Labels: approved

#1227 add missing validations for creative form
  app/models/creative.rb
  test/assets/images/seeds/seed-20x20.png
  test/controllers/advertisement_clicks_controller_test.rb
  test/integration/advertisements_test.rb
  test/test_helper.rb
Labels: approved

#1229 Track fallback clicks on daily summaries table
  Gemfile
  Gemfile.lock
  app/jobs/create_daily_summary_job.rb
  app/models/daily_summary.rb
  app/models/daily_summary_report.rb
  bin/copy_production_db_to_local
  db/migrate/20200421152748_add_fallback_clicks_count_to_daily_summaries.rb
  db/schema.rb
  db/structure.sql
  lib/tasks/jobs.rake
  test/fixtures/daily_summaries.yml
  test/models/daily_summary_test.rb
Labels: approved

#1230 update slack message for paused campaign notification job
  app/jobs/paused_campaign_notification_job.rb
Labels: approved

#1232 update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved

#1231 Fix creative validations
  app/controllers/creatives_controller.rb
  app/javascript/controllers/creative_form_controller.js
  app/models/creative.rb
  app/validators/creative_image_params_validator.rb
  app/views/creatives/_form.html.erb
  test/validators/creative_image_params_validator_test.rb
Labels: approved

#1209 Update the block advertiser feature to use organization_id rather than user_id
  app/controllers/properties_controller.rb
  app/helpers/application_helper.rb
  app/models/campaign.rb
  app/models/concerns/properties/presentable.rb
  app/models/property.rb
  app/views/properties/_details_card.html.erb
  app/views/properties/_form.html.erb
  db/migrate/20200422185634_add_prohibited_organization_ids_to_properties.rb
  db/schema.rb
  db/structure.sql
  lib/tasks/legacy.rake
  lib/tasks/organization_images.rake
  lib/tasks/properties.rake
  test/fixtures/properties.yml
  test/models/property_test.rb
Labels: approved

#1234 don't load ads stylesheet when the theme is `unstyled`
  app/views/advertisements/show.js.erb
  test/system/ads_theme_javascript_test.rb
Labels: approved

#1236 Include callbacks in demo (for demonstration)
  app/controllers/demos_controller.rb
  app/javascript/controllers/ad_demo_controller.js
  app/views/campaigns/_sidebar.html.erb
  app/views/demos/show.html.erb
  app/views/layouts/demo.html.erb
Labels: approved

#1237 fix failing campaign test
  test/models/campaign_test.rb
Labels: approved

#1238 Add comment functionality to users and properties
  app/controllers/property_comments_controller.rb
  app/controllers/user_comments_controller.rb
  app/models/property.rb
  app/models/user.rb
  app/views/properties/_tabs.html.erb
  app/views/property_comments/index.html.erb
  app/views/shared/sidebar_content/_properties.html.erb
  app/views/user_comments/index.html.erb
  app/views/users/_tabs.html.erb
  config/routes.rb
  docs/comments.md
  docs/components.html.erb
  test/components/page_component_test.rb
  test/controllers/property_comments_controller_test.rb
  test/controllers/user_comments_controller_test.rb
  test/test_helper.rb
Labels: approved

#1241 add ability to supply scoped_by param for scopable resources
  app/controllers/concerns/scopable.rb
Labels: approved

#1242 fix comments ui bug and reverse ordering
  app/components/comments_component.html.erb
  app/controllers/campaign_comments_controller.rb
  app/controllers/organization_comments_controller.rb
  app/controllers/property_comments_controller.rb
  app/controllers/user_comments_controller.rb
  app/javascript/controllers/comments_component_controller.js
  app/views/shared/sidebar_content/_footer_admin.html.erb
  app/views/shared/sidebar_content/_footer_advertiser.html.erb
  app/views/shared/sidebar_content/_footer_advertiser_publisher.html.erb
  app/views/shared/sidebar_content/_footer_publisher.html.erb
  app/views/users/_layout.html.erb
  docs/comments.md
Labels: approved

#1243 Upgrade dependencies
  Gemfile
  Gemfile.lock
  README.md
  app/views/layouts/application.html.erb
  app/views/layouts/component_preview.html.erb
  test/components/previews/metabase_component_preview.rb
  test/components/previews/page_component_preview.rb
  test/components/previews/users/avatar_component_preview.rb
  yarn.lock
Labels: approved
